name: Verify Org Config
on:
  pull_request_target:
    branches:
      - master
jobs:
  verify-org-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr

      - name: Peribolos dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.PERIBOLOS_TOKEN }}
        run: |
          echo $GITHUB_TOKEN > $RUNNER_TEMP/token
          docker run --rm \
            -v $RUNNER_TEMP/token:/etc/github/token \
            -v $(pwd)/pr/config.yaml:/etc/config/config.yaml \
            gcr.io/k8s-prow/peribolos:v20230418-23b5d25059 \
            --github-token-path /etc/github/token \
            --config-path /etc/config/config.yaml \
            --fix-org \
            --fix-org-members \
            --fix-team-members \
            --fix-teams \
            --fix-team-repos
